### ISSUE TITLE
Allow user to specify which subject to include in publication

### ISSUE THREAD

**Issue by soichih** [brainlife/brainlife#63]
We currently allow users to specify which datatype to include in the publication. The selection is then applied to *all* currently existing data on all subject within the project and matching data object will be included in the publication. 

Recently, a user wanted to publish a subset of subjects in stead of all subjects within the project. We could update the current datatype selector to allow specifying either all or specific subjects for publication.

**Comment by soichih** [comment]
I've added subject selecter that user can use to specify which subject to include in the publication.

![image](https://user-images.githubusercontent.com/923896/90291679-65812800-de4e-11ea-92f3-fe2210cdd238.png)

If the list is empty, *all* subjects will be selected.

@rjpuzniak @francopestilli 

https://github.com/brainlife/warehouse/commit/c981f64483358598b958cd8b3159e6c088508fe7
https://github.com/brainlife/warehouse/commit/e9c8ea61f5db31a9ce71c39360a726bb63c4b71d

**Comment by francopestilli** [comment]
hi @soichih thanks for implementing this. I have one thought. Given that this is meant to be used mostly to exclude a few special subjects, I wonder whether the menu should allow selection of subjects to "exclude," instead of include. Imagine have hundreds of subjects and wanting to exclude say 5 or 10, in the way this seems to be implemented now, I understand that I would need to click 90 subjects? Wouldn't it be better to select the ones to exclude instead? Say 5 or 10 in our example?

**Comment by soichih** [comment]
Yes, so I've added the "Add all subjects to the list" for that use case. A user can click that button to populate all subjects, then remove the subject they don't want from the list.

If user wants to only include a few subjects out of hundreds, this UI can handle that use case very well also.
